name: Tags and Release

on:
  workflow_run:
    workflows: ["Java CI"]
    branches: [ master ]
    types: [ completed ]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Effect only on new commits
        run: |
          BOUNDARY_COMMIT=$(git rev-list -n 1 --before="2025-04-09" master)
          echo "boundary_commit=$BOUNDARY_COMMIT" >> $GITHUB_OUTPUT

      - name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          release-type: java
          last-release-sha: ${{ env.BOUNDARY_COMMIT }}
          pull-request-title-pattern: "chore: release ${version}"
          version-file: "version.properties"
          extra-files: |
            version.properties
          prerelease: "SNAPSHOT"


          changelog-types: |
            {"feat": {"section": "Features", "hidden": false}, 
             "fix": {"section": "Bug Fixes", "hidden": false},
             "chore": {"section": "Miscellaneous", "hidden": false},
             "docs": {"section": "Documentation", "hidden": false},
             "perf": {"section": "Performance Improvements", "hidden": false},
             "refactor": {"section": "Code Refactoring", "hidden": false}}
          versions-file-section-name: "version"